### PR TITLE
added header

### PR DESCRIPTION
**Pull request by younesr1**
i'll open a real pr once this file becomes more stable

### CODE REVIEW

**Comment by wmmc88** [comment]
i thinnk this repo should have a cmakelists.txt and a makefile to compile the library(this header and the source files that contain the definitions for the acessors). Our fw and ros repos can include the makefile/cmakelists in their own makefile and cmakelists. This ensures that any code here is compiled in the same way(mostly checking for same version of c++)

**Comment by younesr1** [comment]
@wmmc88 i thought this repo wouldnt have any src files. i thought the accessors were short enough to be in the header. this'd mean we dont need to compile this lib

**Comment by wmmc88** [comment]
I think it's better to have src file to make sure this code actually compiles before we merge

**Comment by younesr1** [comment]
this pr only includes the header and src file

**Comment by younesr1** [comment]
@wmmc88 , @qinyang-bao , @jetkov is this pr good to go?

**Review by wmmc88 — APPROVED** [review]
lgtm
@jetkov thoughts?

**Pull request merged**
