### PR TITLE
Add Cmakelists

### PR DESCRIPTION
**Pull request by wmmc88**

### CODE REVIEW

**Review by jetkov — APPROVED** [review]
👍

**Comment by wmmc88** [comment]
ill merge this after i get a pr on sw to accomodate

**Comment by younesr1** [comment]
> ill merge this after i get a pr on sw to accomodate

i havent merged the rosinstall yet, i was waiting for you to make this update

**Comment by wmmc88** [comment]
> > ill merge this after i get a pr on sw to accomodate
> 
> i havent merged the rosinstall yet, i was waiting for you to make this update

should i push to your branch or u just make the changes?

**Comment by younesr1** [comment]
> > > ill merge this after i get a pr on sw to accomodate
> > 
> > 
> > i havent merged the rosinstall yet, i was waiting for you to make this update
> 
> should i push to your branch or u just make the changes?

Just merge this in. Then, on sw ill update the ros dependencies.

**Review by younesr1 — COMMENTED** [review]
lgtm

**Pull request merged**
